-- ════════════════════════════════════════════════════════════════════
--  CinnabyteHQ · 001 · Initial schema
--
--  Paste into Supabase → SQL Editor → Run   (or: supabase db push)
--
--  Tables
--    profiles        people in the workspace
--    requests        internal requests (the core workflow)
--    approvals       sign-off decisions on requests
--    projects        work streams with reported progress
--    tasks           units of work inside a project
--    activity_logs   append-only history of everything that happens
--
--  Security
--    Row Level Security is ON for every table and there are no policies
--    yet, so the public anon key can read/write nothing. The Astro server
--    talks to the database with the service-role key (which bypasses RLS)
--    and never exposes it to the browser. Policies arrive with Supabase
--    Auth — see docs/BACKEND_INTEGRATION.md.
-- ════════════════════════════════════════════════════════════════════


-- ─── Enums ───────────────────────────────────────────────────────────

create type public.user_role        as enum ('admin', 'manager', 'member');
create type public.priority_level   as enum ('low', 'medium', 'high');
create type public.request_category as enum (
  'it_equipment', 'software_access', 'facilities', 'design', 'finance', 'people'
);
create type public.request_status   as enum ('new', 'in_review', 'in_progress', 'completed', 'rejected');
create type public.approval_status  as enum ('pending', 'approved', 'rejected');
create type public.project_status   as enum ('planning', 'in_progress', 'on_hold', 'completed');
create type public.task_status      as enum ('todo', 'in_progress', 'completed');
create type public.activity_action  as enum (
  'created', 'updated', 'status_changed', 'assigned', 'approved', 'rejected',
  'commented', 'completed', 'progress_updated', 'deleted'
);


-- ─── Shared trigger: keep updated_at current ─────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ─── profiles ────────────────────────────────────────────────────────
-- With Supabase Auth, `id` will reference auth.users(id) (see docs).

create table public.profiles (
  id          uuid primary key default gen_random_uuid(),
  full_name   text not null check (char_length(full_name) between 1 and 120),
  email       text not null unique check (position('@' in email) > 1),
  avatar_url  text,
  role        public.user_role not null default 'member',
  job_title   text,                               -- e.g. "Operations Manager"
  team        text,                               -- e.g. "Operations"
  created_at  timestamptz not null default now()
);


-- ─── requests ────────────────────────────────────────────────────────

create table public.requests (
  id            uuid primary key default gen_random_uuid(),
  -- Human-friendly reference shown in the UI as REQ-1042
  number        integer generated by default as identity (start with 1001) unique,
  title         text not null check (char_length(title) between 4 and 120),
  description   text not null check (char_length(description) between 10 and 2000),
  category      public.request_category not null,
  priority      public.priority_level not null default 'medium',
  status        public.request_status not null default 'new',
  requester_id  uuid not null references public.profiles (id) on delete restrict,
  assignee_id   uuid references public.profiles (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index requests_status_idx       on public.requests (status);
create index requests_priority_idx     on public.requests (priority);
create index requests_requester_id_idx on public.requests (requester_id);
create index requests_assignee_id_idx  on public.requests (assignee_id);
create index requests_created_at_idx   on public.requests (created_at desc);

create trigger requests_set_updated_at
  before update on public.requests
  for each row execute function public.set_updated_at();


-- ─── approvals ───────────────────────────────────────────────────────
-- A request can collect several approvals over time (e.g. re-submitted
-- after a rejection) but only one can be pending at once.

create table public.approvals (
  id           uuid primary key default gen_random_uuid(),
  request_id   uuid not null references public.requests (id) on delete cascade,
  approver_id  uuid not null references public.profiles (id) on delete restrict,
  status       public.approval_status not null default 'pending',
  comment      text check (comment is null or char_length(comment) <= 1000),
  approved_at  timestamptz,                       -- when the decision (approve or reject) was made
  created_at   timestamptz not null default now(),

  -- a decision always has a timestamp, a pending approval never does
  constraint approvals_decision_timestamp check ((status = 'pending') = (approved_at is null))
);

create unique index approvals_one_pending_per_request
  on public.approvals (request_id) where status = 'pending';
create index approvals_request_id_idx  on public.approvals (request_id);
create index approvals_approver_id_idx on public.approvals (approver_id, status);
create index approvals_status_idx      on public.approvals (status);


-- ─── projects ────────────────────────────────────────────────────────

create table public.projects (
  id           uuid primary key default gen_random_uuid(),
  name         text not null check (char_length(name) between 2 and 80),
  description  text not null default '' check (char_length(description) <= 1000),
  owner_id     uuid not null references public.profiles (id) on delete restrict,
  status       public.project_status not null default 'planning',
  progress     integer not null default 0 check (progress between 0 and 100),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index projects_status_idx   on public.projects (status);
create index projects_owner_id_idx on public.projects (owner_id);

create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();


-- ─── tasks ───────────────────────────────────────────────────────────

create table public.tasks (
  id           uuid primary key default gen_random_uuid(),
  title        text not null check (char_length(title) between 2 and 160),
  description  text check (description is null or char_length(description) <= 2000),
  project_id   uuid not null references public.projects (id) on delete cascade,
  assignee_id  uuid references public.profiles (id) on delete set null,
  priority     public.priority_level not null default 'medium',
  status       public.task_status not null default 'todo',
  due_date     date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index tasks_project_id_idx  on public.tasks (project_id);
create index tasks_assignee_id_idx on public.tasks (assignee_id);
create index tasks_status_idx      on public.tasks (status);
create index tasks_priority_idx    on public.tasks (priority);
create index tasks_due_date_idx    on public.tasks (due_date);

create trigger tasks_set_updated_at
  before update on public.tasks
  for each row execute function public.set_updated_at();


-- ─── activity_logs ───────────────────────────────────────────────────
-- Written only by the server. Links are nullable (an event can concern a
-- request, a project, a task — or survive after the record is deleted).
-- `metadata` holds structured details for the UI, e.g.
--   {"entity": "request", "title": "Laptop replacement", "from": "new", "to": "in_review"}

create table public.activity_logs (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid references public.profiles (id) on delete set null,
  request_id   uuid references public.requests (id) on delete set null,
  project_id   uuid references public.projects (id) on delete set null,
  task_id      uuid references public.tasks (id) on delete set null,
  action       public.activity_action not null,
  description  text not null,
  metadata     jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

create index activity_logs_created_at_idx on public.activity_logs (created_at desc);
create index activity_logs_user_id_idx    on public.activity_logs (user_id);
create index activity_logs_request_id_idx on public.activity_logs (request_id);
create index activity_logs_project_id_idx on public.activity_logs (project_id);
create index activity_logs_task_id_idx    on public.activity_logs (task_id);


-- ─── Row Level Security ──────────────────────────────────────────────
-- Enabled with no policies = deny by default for the anon/authenticated
-- keys. The server's service-role key bypasses RLS.

alter table public.profiles      enable row level security;
alter table public.requests      enable row level security;
alter table public.approvals     enable row level security;
alter table public.projects      enable row level security;
alter table public.tasks         enable row level security;
alter table public.activity_logs enable row level security;
